version: 2
jobs:
  build_stg:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/escritorio-pagarme
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
            cd functions
            npm install
            cd ..
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-
      - run:
          name: Deploy application
          command: |
            export AWS_ACCESS_KEY_ID=$TEST_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$TEST_ACCESS_KEY_SECRET
            export AWS_REGION=$TEST_AWS_REGION
            sh ./.circleci/setup-tests.sh
            npm run deploy
            node .circleci/invalidate-cdn
  build_prd:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/escritorio-pagarme
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
            cd functions
            npm install
            cd ..
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-
      - run:
          name: Deploy application
          command: |
            export AWS_ACCESS_KEY_ID=$STG_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STG_ACCESS_KEY_SECRET
            export AWS_REGION=$STG_AWS_REGION
            npm run deploy
            node .circleci/invalidate-cdn

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_stg:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).+$/
    - build_prd:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+)$/